export const unionData = [
  {
    level: 1,
    title: "组件",
    path: "",
    active: false,
  },
  {
    level: 2,
    title: "Switch 开关",
    path: "/root/packages-demo/yulang-switch",
    active: false,
  },
  {
    level: 2,
    title: "Button 按钮",
    path: "/root/packages-demo/yulang-button",
    active: true,
  },
  {
    level: 2,
    title: "Slider 滑块",
    path: "/root/packages-demo/yulang-slider",
    active: false,
  },
  {
    level: 2,
    title: "Signaure 签名板",
    path: "/root/packages-demo/yulang-signaure",
    active: false,
  },
  {
    level: 2,
    title: "Upload 上传",
    path: "/root/packages-demo/yulang-upload",
    active: false,
  },
  {
    level: 2,
    title: "canvas 画布",
    path: "/root/packages-demo/yulang-canvas",
    active: false,
  },
  {
    level: 2,
    title: "AnchorPoint 锚点",
    path: "/root/packages-demo/yulang-anchor-point",
    active: false,
  },
  {
    level: 2,
    title: "Icon 图标",
    path: "/root/packages-demo/yulang-icon",
    active: false,
  },
  {
    level: 2,
    title: "DescribeFrame 描述框",
    path: "/root/packages-demo/yulang-describe-frame",
    active: false,
  },
  {
    level: 2,
    title: "Link 文字链接",
    path: "/root/packages-demo/yulang-link",
    active: false,
  },
  {
    level: 2,
    title: "Dialog 对话框",
    path: "/root/packages-demo/yulang-dialog",
    active: false,
  },
  {
    level: 2,
    title: "BackTop 回到顶部",
    path: "/root/packages-demo/yulang-back-top",
    active: false,
  },
  {
    level: 2,
    title: "Checkbox 复选框",
    path: "/root/packages-demo/yulang-checkbox",
    active: false,
  },
  {
    level: 2,
    title: "SwitchCopy 开关Copy",
    path: "/root/packages-demo/yulang-switch-copy",
    active: false,
  },
  {
    level: 2,
    title: "Form 表单",
    path: "/root/packages-demo/yulang-form",
    active: false,
  },
  {
    level: 2,
    title: "Table 表格",
    path: "/root/packages-demo/yulang-table",
    active: false,
  },
  {
    level: 2,
    title: "Notification 通知",
    path: "/root/packages-demo/yulang-notification",
    active: false,
  },
  {
    level: 2,
    title: "Message 消息提示",
    path: "/root/packages-demo/yulang-message",
    active: false,
  },
  {
    level: 2,
    title: "Loading 加载中",
    path: "/root/packages-demo/yulang-loading",
    active: false,
  },
  {
    level: 2,
    title: "Tree 树",
    path: "/root/packages-demo/yulang-tree",
    active: false,
  },
  {
    level: 2,
    title: "Leader 引导",
    path: "/root/packages-demo/yulang-leader",
    active: false,
  },
  {
    level: 2,
    title: "Select 下拉框",
    path: "/root/packages-demo/yulang-select",
    active: false,
  },
  {
    level: 2,
    title: "Tabs 标签页",
    path: "/root/packages-demo/yulang-tabs",
    active: false,
  },
  {
    level: 2,
    title: "Divider 分割线",
    path: "/root/packages-demo/yulang-divider",
    active: false,
  },
  {
    level: 2,
    title: "Input 输入框",
    path: "/root/packages-demo/yulang-input",
    active: false,
  },
  {
    level: 2,
    title: "ScrollInfinite 无限滚动",
    path: "/root/packages-demo/yulang-scroll-infinite",
    active: false,
  },
  {
    level: 2,
    title: "Popover 弹出框",
    path: "/root/packages-demo/yulang-popover",
    active: false,
  },
  {
    level: 2,
    title: "TimePicker 时间选择器",
    path: "/root/packages-demo/yulang-time-picker",
    active: false,
  },
  {
    level: 2,
    title: "Tooltip 文字提示",
    path: "/root/packages-demo/yulang-tooltip",
    active: false,
  },
];
